language: rust

rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo build
#  - cargo test
#  - cargo doc --no-deps
#after_success:
#  - travis-cargo --only nightly doc-upload
#env:
#  global:
#    - secure: ""

notifications:
  email:
    on_success: never
os:
  - linux
  - osx
